# Generated by Django 3.1.5 on 2021-01-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('client_member_id', models.CharField(max_length=30)),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
