# Generated by Django 3.1.5 on 2021-01-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcore', '0004_auto_20210107_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='account_id',
            new_name='account',
        ),
    ]
