# Generated by Django 3.1.5 on 2021-01-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcore', '0006_auto_20210107_0453'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('phone_number', 'account_id'), name='unique_phone_number'),
        ),
    ]
