# Generated by Django 3.1.5 on 2021-01-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcore', '0007_auto_20210107_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
