# Generated by Django 3.1.5 on 2021-01-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcore', '0010_auto_20210110_2334'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_phone_number',
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('phone_number', 'account_id'), name='unique_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('client_member_id', 'account_id'), name='unique_client_member_id'),
        ),
    ]
